services:
  - type: web
    name: expressgo-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "python -m gunicorn bus_ticket_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "your_supabase_pooler_url"
